### ISSUE TITLE
模型咨询

### ISSUE THREAD

**Issue by ChaoII** [Zheng-Bicheng/AdaFacePaddleCLas#1]
你好：
看到您在aistudio上提供的训练好的模型，为啥那么大？

**Comment by Zheng-Bicheng** [comment]
您是说导出前的模型吗？导出前的模型非常大是正常的，导出为PaddleInference或者ONNX就不会大了。因为导出后的模型只包含了backbone，而导出前的模型还有全连接层。

**Comment by ChaoII** [comment]
> 您是说导出前的模型吗？导出前的模型非常大是正常的，导出为PaddleInference或者ONNX就不会大了。因为导出后的模型只包含了backbone，而导出前的模型还有全连接层。

原来如此，谢谢哈。
